# Generated by Django 2.2.1 on 2019-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('D', 'Date'), ('I', 'Integer'), ('T', 'Text')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
