# Generated by Django 2.2.1 on 2019-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0002_parameter_parameter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=200, verbose_name='Asset number')),
                ('serial_number', models.CharField(max_length=200, verbose_name='Serial number')),
                ('instance_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
        ),
    ]
