# Generated by Django 2.2.1 on 2019-05-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0003_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='parent_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
