# Generated by Django 2.2.1 on 2019-05-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0004_assets_parent_instance_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
