# Generated by Django 2.2.1 on 2019-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0005_auto_20190517_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('D', 'Date'), ('I', 'Integer'), ('T', 'Text'), ('B', 'Boolean')], max_length=1),
        ),
    ]
