# Generated by Django 2.2.1 on 2019-06-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0006_auto_20190520_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('D', 'date_value'), ('I', 'number_value'), ('T', 'text_value'), ('B', 'boolean_value')], max_length=1),
        ),
    ]
