# Generated by Django 2.2.1 on 2019-06-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0007_auto_20190603_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_group',
            field=models.CharField(default='qwe', max_length=200, verbose_name='Asset group'),
            preserve_default=False,
        ),
    ]
