# Generated by Django 2.2.1 on 2019-06-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0008_asset_asset_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='item_type',
            field=models.CharField(default='AG', max_length=2, verbose_name='Item type'),
            preserve_default=False,
        ),
    ]
