# Generated by Django 2.2.1 on 2019-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0009_asset_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='item_type',
            field=models.CharField(choices=[('RB', 'Rebuildable'), ('AG', 'Asset group')], max_length=2, verbose_name='Item type'),
        ),
    ]
