# Generated by Django 2.2.3 on 2019-08-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0010_auto_20190603_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetHierarchy',
        ),
    ]
