# Generated by Django 2.2.4 on 2019-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0011_delete_assethierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='parent_instance_id',
        ),
        migrations.AlterField(
            model_name='asset',
            name='instance_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
