# Generated by Django 2.2.4 on 2019-08-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0012_auto_20190827_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parent_instance_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oebs.Asset'),
            preserve_default=False,
        ),
    ]
