# Generated by Django 2.2.4 on 2019-08-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oebs', '0013_asset_parent_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oebs.Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
