# Generated by Django 2.2.4 on 2019-09-10 09:42

from django.db import migrations
from ahi import settings


def init_parameters(apps, schema_editor):
    """
    Populate default values to the parameters model
    """

    parameter = apps.get_model("oebs", "Parameter")

    # delete old one if exists
    parameter.objects.filter(name__in=['is_sync_hierarchy', 'root_asset']).delete()

    # is_sync_hierarchy
    parameter(name="is_sync_hierarchy", parameter_type="B",
              boolean_value=True).save()

    # root_asset
    parameter(name="root_asset", parameter_type="I",
              number_value=settings.DEFAULT_ASSET_ID).save()


def drop_parameters(apps, schema_editor):
    # delete new parameters

    parameter = apps.get_model("oebs", "Parameter")

    parameter.objects.filter(name__in=['is_sync_hierarchy', 'root_asset']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('oebs', '0014_auto_20190827_1140'),
    ]

    operations = [
        migrations.RunPython(init_parameters, drop_parameters)
    ]
